const CONNECT = 'CONNECT';
const CREATE = 'CREATE';
const CREATED = 'CREATED';
const JOIN = 'JOIN';
const JOINED = 'JOINED';
const UPDATE = 'UPDATE';
const PLAY = 'PLAY';
const FOODATE = 'FOODATE';
const DIRECTIONCHANGE = 'DIRECTIONCHANGE'

module.exports = { CONNECT, CREATE, CREATED, JOIN, JOINED, UPDATE, PLAY, FOODATE, DIRECTIONCHANGE }