const TAB_KEY_CODE = 9;
const ESCAPE_KEY_CODE = 27;
const IS_BACKDROP_PRESENT = true;
const ON_BACKDROP_CLOSE = true;
const BACKDROP_MODAL_CLOSE_ID = 'modal-container';
const IS_CLOSE_BUTTON_PRESENT = true;
const ON_ESCAPE_CLOSE = true;

// values is in px
const MAX_MODAL_WIDTH = 350;
const MAX_MODAL_HEIGHT = 400;

export {
  TAB_KEY_CODE,
  ESCAPE_KEY_CODE,
  IS_BACKDROP_PRESENT,
  ON_BACKDROP_CLOSE,
  BACKDROP_MODAL_CLOSE_ID,
  IS_CLOSE_BUTTON_PRESENT,
  ON_ESCAPE_CLOSE,
  MAX_MODAL_WIDTH,
  MAX_MODAL_HEIGHT,
};
